interface ProjectInfo {
    Title: string,
    Description: string,
    Badges: Array<string>,
    Link: string,
    GitHub: string
}

export const transcript: Array<ProjectInfo> = [
    {
        Title: 'Computer Science Courses',
        Description: "Descriptions taken from the Kansas State University course catalog, classes listed in reverse chronological order",
        Badges: [],
        Link: '',
        GitHub: ''
    },
    {
    Title: 'CIS 575 - Introduction to Algorithm Analysis',
        Description: 'An introduction to mathematical analysis of time- and space-complexity of algorithms, including worst-case, average-case, and amortized complexity. An examination of various algorithmic designs, such as greedy algorithms, divide-and-conquer algorithms, and dynamic programming algorithms. Techniques for proving correctness of algorithms.',
        Badges: ['Big O Notation'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 415 - Ethics and Conduct for Computing Professionals',
        Description: "A study of the ethical issues raised by computing technologies and the impact on society. Exploration of how one might justify actions in regard to ethical dilemmas within the fields of technology, computer science, information security, and artificial intelligence. Other topics include an examination of terminology used, Profession Codes of Conduct for computer science professionals, ethics of software development, and ethical issues relating to privacy and intellectual property in cyberspace.",
        Badges: [],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'MIS 670 - Social Media Analytics and Web Mining',
        Description: "This course is an in-depth study of a broad range of topics and techniques in the areas of social media analytics, web mining and social network analysis. Emphasis is on fundamentals of data acquisition from the web and social media platforms, transformation of these unstructured data into structured format, advanced data processing techniques for analysis, business intelligence through web crawling, analysis of web and social media data using classification, clustering, and association techniques, sentiment analysis (or opinion mining) for business decisions, visualization of unstructured data, and social network analysis.",
        Badges: ['Python', 'Pandas', 'Selenium', 'Anaconda'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 505 - Introduction to Programming Languages',
        Description: "History, programming language concepts including type, scope and extent, abstraction mechanisms and control; programming paradigms, including one or more of logic, functional, and object-oriented programming, and programming languages supporting the selected paradigms; interpreters, compilers and virtual machines for the selected languages; storage management and garbage collection; type checking and type inference.",
        Badges: ['Ocaml'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 450 - Computer Architecture and Operations ',
        Description: "Introduction to modern computer architectures: register transfer abstraction, addressing modes, basic operations (data transfer, arithmetic/logic, and control operations). Basic Operating System concepts and operations. Understanding relationships of higher-level language constructs to corresponding assembly instruction sequences generated by compilers. Introduction to interrupts and low-level I/O operations.",
        Badges: ['Assembly', 'Bash'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 501 - Software Architecture and Design ',
        Description: "Principles and patterns for design and structure of software, development of object-oriented models, examples of software architecture.",
        Badges: ['C#', 'UML', 'Windows Forms'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 400 - Object-Oriented Design, Implementation, and Testing ',
        Description: "A study of concepts and techniques used to produce quality software programs. Object-oriented concepts, models, execution environments, design and testing techniques. Extensive application of these concepts and techniques to the development of non-trivial software programs.",
        Badges: ['C#', 'WPF', 'UML'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 301 - Logical Foundations of Programming',
        Description: "Logical formalisms used to model and reason about computer systems. Propositional and predicate logic, syntax, semantics, and proof theory; soundness and completeness issues. Mathematical induction. Program verification: invariants and program logics.",
        Badges: ['Scala', 'Slang', 'Serium Logika'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 300 - Data and Program Structures ',
        Description: "A study of common data and program structures together with associated algorithms. Topics include interfaces, design patterns, arrays, stacks, queues, lists, trees, hash tables, recursion, binary search, and tree traversals. Experience with both use and implementation of these structures and algorithms using a modern programming language. Discussion of tradeoffs involving performance and software maintainability.",
        Badges: ['C#'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 308 - C Language Laboratory',
        Description: "Fundamentals of programming in C.",
        Badges: ['C'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 200 - Programming Fundamentals ',
        Description: "Principles of algorithm design and their application to procedural programming: state, control structures, methods. Patterns of conditional and iterative control structure.  Program testing. Introduction to arrays, classes, and objects.  Programming projects.",
        Badges: ['Java'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'ECE 241 - Introduction to Electrical and Computer Engineering ',
        Description: "An introduction to embedded systems and DC circuitry.  Embedded systems focusing on the C programming language, number systems, and data/logical operations. DC circuitry focused on basic circuit theory including voltage, current, ohm’s law, and basic circuit components. Includes laboratory work (e.g., with multimeters and oscilloscopes) and circuit prototyping.",
        Badges: ['Soldering', 'Arduino', 'C'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'CIS 115 - Introduction to Computing Science',
        Description: "A survey of the discipline of Computing Science and its interaction with other disciplines, incorporating historical development, theories, and tools of Computing Science (algorithm design and programming). Topics include: mechanical computers, digital computers, bioinformatics, microcontrollers, robotics, security, scientific computing, simulation, and web technologies.",
        Badges: ['Python', 'HTML/CSS/JavaScript'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'General Education Courses',
        Description: "",
        Badges: [],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'GEOL 200 - Earth Through Time ',
        Description: "Earth Through Time provides a comprehensive survey of Earth’s 4.5 billion year history. It explores the major events that have shaped the physical and biological development of Earth and how processes like plate tectonics and climate change interact with life, forming an integrated system.",
        Badges: ['Badge 1', 'Badge 2'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'Example',
        Description: "Description",
        Badges: ['Badge 1', 'Badge 2'],
        Link: '',
        GitHub: ''
    },
    {
        Title: 'Example',
        Description: "Description",
        Badges: ['Badge 1', 'Badge 2'],
        Link: '',
        GitHub: ''
    },
]

// {
//     Title: 'Example',
//     Description: "Description",
//     Badges: ['Badge 1', 'Badge 2'],
//     Link: '',
//     GitHub: ''
// },